seq = """CACAAACACAGCAACTAATCCACCAGTAGCTTGAGAAGATGAGCACAATCTCACAGTGACTATAAGCAGTACACAGCGCCAGTCAACAACAATAACTATCATCTGAGAA
         ATTCAGGGAAATACTCGACGTACACTAGAAAAATATATCGTAGGACCATCGTCCTCATCTCCTTCCCGAGTTCCCATGTCTTTGGCTGCGGAAATAGCTGAGGAGAACC
         TGCGCCTTTTCTCTTGCGCGTGGTGTTCCTGACTGTGACAGTGCGACTAAAGGGGGCACGGCATCCTCTTGAAGAACTATGTTGCAAAACCTGCTGCTGTTTGTGCATA
         GCTGAAGCAATGCCGCGGTAGCA TTTTCCTTCGCTTTCGCTGAACCCAGTTCGACAACTTCAACAAGGGCCGGAATACCACGCGCCTGCCCAATCGCAGTCCTTCCTT
         CTGGTATCGTAGCAAGATTTGCCAAGACAGCTACAGCTTTATCGACCATTCCAGCAGCAGGGTCCATAAGCTCAACTAGGTGCTTCAATGCATCAGCTTGCACAATTCG
         ACCCTTGTTCTCATGAAGTATGGATAAATTAAACAATGCAGTAACCGCATCTTTCTTTCCTCGTGGGCTCCCATTTCCCAGCAAGTCCACGAGAGGCTTTACAGCACCA
         GATCGCCCTATCCTCACTCTGTTTTCTTCAATAATTGAGAGACTGAA"""


for char in seq:
    if char == 'A':
        seq2 += 'T'
    elif char == 'T':
        seq2 += 'A'
    elif char == 'C':
        seq2 += 'G'
    elif char == 'G':
        seq2 += 'C'

seq2 = seq2[::-1]

print (seq2)