seq = """CACAAACACAGCAACTAATCCACCAGTAGCTTGAGAAGATGAGCACAATCTCACAGTGACTATAAGCAGTACACAGCGCCAGTCAACAACAATAACTATCATCTGAGAA
         ATTCAGGGAAATACTCGACGTACACTAGAAAAATATATCGTAGGACCATCGTCCTCATCTCCTTCCCGAGTTCCCATGTCTTTGGCTGCGGAAATAGCTGAGGAGAACC
         TGCGCCTTTTCTCTTGCGCGTGGTGTTCCTGACTGTGACAGTGCGACTAAAGGGGGCACGGCATCCTCTTGAAGAACTATGTTGCAAAACCTGCTGCTGTTTGTGCATA
         GCTGAAGCAATGCCGCGGTAGCA TTTTCCTTCGCTTTCGCTGAACCCAGTTCGACAACTTCAACAAGGGCCGGAATACCACGCGCCTGCCCAATCGCAGTCCTTCCTT
         CTGGTATCGTAGCAAGATTTGCCAAGACAGCTACAGCTTTATCGACCATTCCAGCAGCAGGGTCCATAAGCTCAACTAGGTGCTTCAATGCATCAGCTTGCACAATTCG
         ACCCTTGTTCTCATGAAGTATGGATAAATTAAACAATGCAGTAACCGCATCTTTCTTTCCTCGTGGGCTCCCATTTCCCAGCAAGTCCACGAGAGGCTTTACAGCACCA
         GATCGCCCTATCCTCACTCTGTTTTCTTCAATAATTGAGAGACTGAA"""

seq2 = seq.replace('T', 'U')

print (seq2)